Added Organization.CreateOrUpdate
Speedygeek/ZendeskApi_v2 pull request #515
Opened 2021-04-13 13:02 UTC by MelGrubb

I added the missing methods and related tests.

2021-04-13 13:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Speedygeek/ZendeskApi_v2?pullRequest=515) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Speedygeek/ZendeskApi_v2?pullRequest=515) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Speedygeek/ZendeskApi_v2?pullRequest=515) it.</sub>

2021-04-13 16:02 UTC, mozts2005 reviewed
please, have a look at the code changes.

2021-04-13 16:02 UTC, mozts2005 commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.AreEqual(update.Organization.Id, res.Organization.Id);
```csharp
            Assert.That(update.Organization.Id, Is.EqualTo(res.Organization.Id));
            Assert.That(update.Organization.Name,  Is.EqualTo(res.Organization.Name));

            Assert.That( await api.Organizations.DeleteOrganizationAsync(res.Organization.Id.Value), Is.True);
```

2021-04-13 16:02 UTC, mozts2005 commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.Greater(res.Organization.Id, 0);
```csharp
Assert.That(res.Organization.Id, Is.GreaterThan(0));
```

2021-04-13 16:06 UTC, MelGrubb commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.Greater(res.Organization.Id, 0);
These tests are direct copies of the style of other existing tests in the same and other files. Isn't consistency better?

2021-04-13 16:07 UTC, MelGrubb commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.Greater(res.Organization.Id, 0);
Also, you should really look at an assertion library like Shouldly. It makes the code AND the error messages easier to read.

2021-04-13 16:10 UTC, mozts2005 commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.Greater(res.Organization.Id, 0);
I am working on changing all test cases to this format. When using the ```Assert.That``` syntax the error messages are the same style that Shouldly uses with out the need for a separate dependency.

2021-04-13 16:32 UTC, mozts2005 requested changes

2021-04-13 16:32 UTC, mozts2005 commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.True(api.Organizations.DeleteOrganization(res.Organization.Id.Value));
```suggestion
            Assert.That(update.Organization.Id, Is.EqualTo(res.Organization.Id));
            Assert.That(update.Organization.Name,  Is.EqualTo(res.Organization.Name));

            Assert.That( await api.Organizations.DeleteOrganizationAsync(res.Organization.Id.Value), Is.True);
```

2021-04-13 16:32 UTC, mozts2005 commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.True(api.Organizations.DeleteOrganization(res.Organization.Id.Value));
```suggestion
            Assert.That(update.Organization.Id, Is.EqualTo(res.Organization.Id));
            Assert.That(update.Organization.Name,  Is.EqualTo(res.Organization.Name));

            Assert.That(api.Organizations.DeleteOrganization(res.Organization.Id.Value), Is.True);
```

2021-04-14 12:26 UTC, MelGrubb commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.Greater(res.Organization.Id, 0);
Does this hold for the other assertions as well?
```
Assert.That(update.Organization, Is.EqualTo(res.Organization.Id));
Assert.That(update.Organization.Name, Is.EqualTo(res.Organization.Name));
Assert.That(api.Organizations.DeleteOrganization(res.Organization.Id.Value), Is.True);
```

2021-04-14 12:32 UTC, MelGrubb commented on test/ZendeskApi_v2.Test/OrganizationTests.cs
> +            Assert.Greater(res.Organization.Id, 0);
Asserts have been updated.

You should be able to make a change everywhere in one clean sweep with some regex search and replace. I've certainly swapped between MSTest and NUnit that way before. That would keep the code in an internally-consistent state by changing them all at once. I'm not saying they're FUN to write, but you spend 15-30 minutes wrestling with RegEx and then watch the magic happen everywhere all at once. Satisfying.

2021-04-15 18:54 UTC, mozts2005 approved these changes

2021-04-15 18:54 UTC, merged