Added BulkCreateUpdateUsers and BulkCreateUpdateUsersAsync
Speedygeek/ZendeskApi_v2 pull request #559
Opened 2022-08-01 10:21 UTC by sumathydoss

This is to create or update many users using "users/create_many.json" api.

2022-08-01 16:15 UTC, mozts2005 commented
@sumathydoss can you please add test cases for this PR and I will be happy to approve this request.

2022-08-02 00:41 UTC, sumathydoss commented
Sure.  I will add the test cases.

From: Elizabeth Schneider ***@***.***>
Sent: Tuesday, 2 August 2022 12:15 am
To: Speedygeek/ZendeskApi_v2 ***@***.***>
Cc: Sumathy (.asia) ***@***.***>; Mention ***@***.***>
Subject: Re: [Speedygeek/ZendeskApi_v2] Added BulkCreateUpdateUsers and BulkCreateUpdateUsersAsync (PR #559)


@sumathydoss<https://github.com/sumathydoss> can you please add test cases for this PR and I will be happy to approve this request.

—
Reply to this email directly, view it on GitHub<https://github.com/Speedygeek/ZendeskApi_v2/pull/559#issuecomment-1201413984>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATCAA4JOYOKGTBD3FOJE5UDVW7ZZRANCNFSM55HAS5CA>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-08-02 21:20 UTC, mozts2005 requested changes

2022-08-02 21:20 UTC, mozts2005 commented on tests/ZendeskApi_v2.Tests/UserTests.cs
> +
- Fixed formatting issues (removed whitespace) 
- added required test attribute
- updated test case to cleanup test data. 

```suggestion

        [Test]
        public async Task CanBulkCreateUpdateUsersAsync()
        {
            var users = new List<User> {
                new User
                {
                     Name = Guid.NewGuid().ToString("N") + " " + Guid.NewGuid().ToString("N"),
                     Email = Guid.NewGuid().ToString("N") + "@test.com",
                     Verified = true
                },
                new User
                {
                    Name = Guid.NewGuid().ToString("N") + " " + Guid.NewGuid().ToString("N"),
                    Email = Guid.NewGuid().ToString("N") + "@tester.com",
                    Verified = true
                },
            };
            var updateResp = await Api.Users.BulkCreateUpdateUsersAsync(users);
            var job = await Api.JobStatuses.GetJobStatusAsync(updateResp.JobStatus.Id);
            var count = 0;
            while (job.JobStatus.Status.ToLower() != "completed" && count < 10)
            {
                await Task.Delay(1000);
                job = await Api.JobStatuses.GetJobStatusAsync(updateResp.JobStatus.Id);
                count++;
            }
            Assert.That(job.JobStatus.Status.ToLower(), Is.EqualTo("completed"));
            
            
            foreach(var u in users)
            {
                var rsp = await Api.Users.SearchByEmailAsync(u.Email);
                if(rsp.Users.Any())
                {
                   await Api.Users.DeleteUserAsync(rsp.Users[0].Id.Value);
                }
            }
        }
    }
}
```

2022-08-03 14:58 UTC, merged